### ISSUE TITLE
frappe-gantt中moment报错

### ISSUE THREAD

**Issue by kevinlvhsl** [hustcc/gantt-for-react#1]
我在使用组件时，
import ReactGantt from 'gantt-for-react'
<ReactGantt tasks={tasks}
                        viewMode={viewMode}
                        customPopupHtml={customPopupHtml}
                        scrollOffsets={scrollOffsets}
                        />
正常引用，跟demo中代码一样， 但是会出现错误、
index.js:133452  Uncaught ReferenceError: moment is not defined
说frappe-gantt中的moment不存在， 我项目中也安装了moment？
是什么原因？

**Comment by hustcc** [comment]
在代码：

```js
import ReactGantt from 'gantt-for-react'
```

下面加入一行：

```js
import moment from 'moment';
```

**Comment by kevinlvhsl** [comment]
加了， 也没用， 因为当前组件里并没有用到moment， 报错的文件是frappe-gantt.js。你在写demo的时候为什么引用moment.min.js？

**Comment by hustcc** [comment]
加了，在这里：https://github.com/hustcc/gantt-for-react/blob/master/index.html#L19

**Comment by kevinlvhsl** [comment]
moment js 我也引用了。还是报错的。           你index中引用的snap.svg-min.js 和moment.min.js 都是必须依赖的吗？ 怎么不用npm的方式引入？ 能出一个稍微详细一点使用gantt-for-react的doc吗？
可以直接给你发邮件吗？ 353030799@qq.com

**Comment by hustcc** [comment]
本项目只是 https://github.com/frappe/gantt 的 react 包装，具体的使用细节还需要到原项目，按照他的使用原则来使用。

**Comment by hustcc** [comment]
You can submit your case on https://github.com/frappe/gantt/issues/31.

Or 

 - import `moment.js` in your html file with `script` tag.
 - add moment.js in webpack as global.
