### ISSUE TITLE
Uncaught ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by tangsiwen** [hustcc/gantt-for-react#3]
您好，请问我使用该组件一直报这个错，我已经引入了moment包还是不行

**Comment by tangsiwen** [comment]
已经解决了

**Comment by tpinne** [comment]
How did you solve it?

**Comment by hustcc** [comment]
import moment with script tab in HTML.

**Comment by tpinne** [comment]
Sadly that's not an option to go with here :(

**Comment by hustcc** [comment]
1. import moment with script tag.
2. npm install moment.

gantt needs it.

**Comment by tpinne** [comment]
I know that gantt needs moment and we have it already included in our project. But importing it via a script tag is not an option. Not moment in general, which I haven't been clearly about in my answer. Sorry for the confusion.

**Comment by hustcc** [comment]
You can submit your case on https://github.com/frappe/gantt/issues/31.

Or 

 - import `moment.js` in your html file with `script` tag.
 - add moment.js in webpack as global.
