### ISSUE TITLE
提示moment未定义， 我自己打包老失败。不知道什么原因

### ISSUE THREAD

**Issue by xingyibiao** [hustcc/gantt-for-react#4]
提示moment未定义， 我自己打包老失败。不知道什么原因

**Comment by hustcc** [comment]
原项目 frappe-gantt 对于依赖 moment 处理不是很好。

这个问题可以给原项目提一个 pr，周末我花时间看看这个问题吧，不少人问到这个问题！

**Comment by hustcc** [comment]
You can submit your case on https://github.com/frappe/gantt/issues/31.

**Comment by hustcc** [comment]
You can submit your case on https://github.com/frappe/gantt/issues/31.

Or 

 - import `moment.js` in your html file with `script` tag.
 - add moment.js in webpack as global.
