### ISSUE TITLE
ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by ajAnshul** [hustcc/gantt-for-react#5]
I followed the example
[https://github.com/hustcc/gantt-for-react/blob/master/demo/GanttComponent.jsx](https://github.com/hustcc/gantt-for-react/blob/master/demo/GanttComponent.jsx).

But while running it saying moment is not defined.

**Comment by hustcc** [comment]
You can submit your case on https://github.com/frappe/gantt/issues/31.

Or import `moment.js` in your html file with `script` tag.
