### ISSUE TITLE
how to run the app without error 

### ISSUE THREAD

**Issue by sbaiti** [hustcc/gantt-for-react#6]
https://codesandbox.io/s/k2wqq89vjo

this a link sandbox that didn't work the app how to run it ?

**Comment by Markus-bt** [comment]
As it says, task is not a function. I cannot see any definition of tasks and, by the way, no definition of viewmode or even the state as such.
Use the whole example as seen in the link to the code on the code-page, it should include everything you need.

**Comment by hustcc** [comment]
New version v0.2.0 released.

Demo see `demo` folder.
