### ISSUE TITLE
Error when build

### ISSUE THREAD

**Issue by gravitano** [hustcc/gantt-for-react#9]
Hey,

I got errors when building react app that use this package. I know that react don't compile the code that not ES5. Can someone help me to fix it?

```
yarn run v1.7.0
$ cross-env REACT_APP_BUILD_ENV=production react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/frappe-gantt/src/svg_utils.js:9 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.

```

**Comment by hustcc** [comment]
Please send issue on repo frappe-gantt.

**Comment by Maskik** [comment]
[create-react-app Troubleshooting](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) -  It helps for me.
You can import module as your component from src/
In this case babel will compile source code of frappe-gantt in right way.
